### PR TITLE
Add MongoDB support with PyMongo

### PR DESCRIPTION
**Pull request by daniell-olaitan**
- Implemented `MongoDB` support in the codebase using `PyMongo`.

- Added test case to ensure `MongoDB` integration works correctly.

- Updated `requirements.txt` and `setup.py` to include `PyMongo` and other necessary dependencies.

- Maintained consistency with existing database integrations (`MariaDB`, `MySQL`, `PostgreSQL`).

- Updated `README.md` to include `MongoDB`.

### CODE REVIEW

**Comment by evangelosmeklis** [comment]
@daniell-olaitan  Hello and thanks for contributing. Does this work with MongoDB compass? Because I can't find the user and password in mongodb compass. Have you tested this with a real mongodb database on your machine and it works?

**Review by evangelosmeklis — APPROVED** [review]
Code seems good and in line with the rest. But we should add the option to not have user and password for databases that do not require it. Same for the others (mysql, mariadb, postgres, sqlite(when we add it) etc)

**Comment by daniell-olaitan** [comment]
@evangelosmeklis Hello, thanks for your feedback!

To be transparent, I have tested the MongoDB integration using the **MongoDB shell**, and it works perfectly. However, I have not tested it with **MongoDB Compass** specifically. 

If necessary, I can look into testing with Compass or assist with any issues you encounter when using it in Compass.

Let me know if you'd like any further clarification or testing!

**Comment by evangelosmeklis** [comment]
@daniell-olaitan hey approved both pull requests. I believe on of the problems i had with mongodb compass was that I didnt have any password or username so the cli of peepdb compained. I will add an issue to make user and password for all databases optional so that it can work when users don't have credentials on their databases (which is unsafe but ok). If you want you can either try that issue or try with mongodb compass, whatever is ok with you

**Comment by daniell-olaitan** [comment]
@evangelosmeklis okay, thanks.

**Comment by evangelosmeklis** [comment]
@daniell-olaitan thanks a lot for contributing and for the good work!

**Comment by daniell-olaitan** [comment]
@evangelosmeklis I'm looking forward to contributing more.

**Pull request merged**
